"""Add page_count and error_message to documents

Revision ID: 35fe1ba9cb29
Revises: 0d5b108bbd89
Create Date: 2025-12-25 05:02:12.813612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35fe1ba9cb29'
down_revision: Union[str, Sequence[str], None] = '0d5b108bbd89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True, comment='Number of pages in the PDF document'))
    op.add_column('documents', sa.Column('error_message', sa.String(length=1000), nullable=True, comment='Error message if processing failed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'page_count')
    # ### end Alembic commands ###
