"""Add CHECK constraint for non-negative processing_duration

Revision ID: 0d5b108bbd89
Revises: 6f0d5a1141af
Create Date: 2025-12-24 19:21:49.994307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5b108bbd89'
down_revision: Union[str, Sequence[str], None] = '6f0d5a1141af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
