"""Add CHECK constraint for non-negative file_size

Revision ID: 6f0d5a1141af
Revises: 9d2cdc716c25
Create Date: 2025-12-24 19:11:06.547651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f0d5a1141af'
down_revision: Union[str, Sequence[str], None] = '9d2cdc716c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
